W4D5/muisic_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i(new create show)
  resource :session, only: %i(new create destroy)

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end
  resources :tracks, except: [:new, :index]
end

W4D5/muisic_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :integer          not null
#  alb_type   :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :band_id, :title, :year, :alb_type, presence: true
  validates :alb_type, inclusion: { in: %w(Live Studio),
    message: "%(value) is not a valid album type" }

  belongs_to :band
  has_many :tracks
end

W4D5/muisic_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums
  has_many :tracks,
  through: :albums,
  source: :tracks
end

W4D5/muisic_app/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint(8)        not null, primary key
#  album_id   :integer          not null
#  title      :string           not null
#  ord        :integer          not null
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  track_type :string
#

class Track < ApplicationRecord
  validates :album_id, :title, :ord, :track_type, presence: true

  belongs_to :album
  has_one :band

end

W4D5/muisic_app/app/models/user.rb
require 'bcrypt'
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness:true
  validates :password_digest, presence: {message: 'Password can\'t be blank'}
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    match = BCrypt::Password.new(user.password_digest).is_password?(password)
    return match ? user : nil
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end
end

W4D5/muisic_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController


  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
    @current_band = Band.find(params[:band_id])
  end

  def create
    @album = Album.new(album_params)
    @album.band_id = params[:album][:band].to_i
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    @album.band_id = params[:album][:band].to_i
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors].errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    band = @album.band
    Album.all.delete(@album)
    redirect_to band_url(band)
  end

  # def current_band
  #   @band = Band.find(params[:album][:band].id)
  # end
  private

  def album_params
    params.require(:album).permit(:title, :year, :alb_type)
  end
end

W4D5/muisic_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_login
    redirect_to new_session_url if current_user.nil?
  end
end

W4D5/muisic_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end
  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band && @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = ["Can't find the band or Can't save the band"]
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    Band.all.delete(@band)
    redirect_to bands_url
  end


  private

  def band_params
    params.require(:band).permit(:name)
  end
end

W4D5/muisic_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flsh.now[:errors] = ["Invalid email or/and password"]
      render :new
    end 
  end

  def destroy
    logout
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5/muisic_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def show
    @track = Track.find(params[:id])
  end

  def new
    @track = Track.new
    @current_album = Album.find(params[:album_id])
  end

  def create
    @track = Track.new(track_params)
    @track.album_id = params[:track][:album].to_i
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])
    @track.album_id = params[:track][:album].to_i
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors].errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    album = @track.album
    Track.all.delete(@track)
    redirect_to album_url(album)
  end


  private
  def track_params
    params.require(:track).permit(:title, :ord, :lyrics, :track_type)
  end
end

W4D5/muisic_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5/muisic_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W4D5/muisic_app/app/helpers/application_helper.rb
module ApplicationHelper

  def authen_form
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{h(form_authenticity_token)}\"".html_safe
  end
end

W4D5/muisic_app/app/helpers/bands_helper.rb
module BandsHelper
end

W4D5/muisic_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W4D5/muisic_app/app/helpers/tracks_helper.rb
module TracksHelper
end

W4D5/muisic_app/app/helpers/users_helper.rb
module UsersHelper
end

W4D5/muisic_app/app/views/albums/edit.html.erb
<h1>UPDATE <%= @album.title.upcase %> ALBUM!</h1>


<form class="update_album" action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= authen_form %>

  <label for="album_title">Title
    <input type="text" name="album[title]" value="<%= @album.title %>">
  </label>
  <br><br>


  <label for="album_band">Band
    <select name="album[band]">
      <% Band.all.each do |band| %>
        <option value="<%= band.id %>" <%= @album.band == band ? "selected" : "" %>>
          <%= band.name %>
        </option>
      <% end  %>
    </select>
  </label>
  <br><br>

  <label for="album_type">Live
    <input type="radio" name="album[alb_type]" value="Live"
     <%= @album.alb_type == "Live" ? "checked" : "" %> >
  </label>
  <label for="album_type">Studio
    <input type="radio" name="album[alb_type]" value="Studio"
     <%= @album.alb_type == "Studio" ? "checked" : '' %> >
  </label>
  <br><br>

  <label for="album_year">Year
    <input type="text" name="album[year]" value="<%= @album.year %>">
  </label>
  <br><br>

  <input type="submit" value="Submit">

</form>

W4D5/muisic_app/app/views/albums/new.html.erb
<h1>NEW <%= @current_band.name.upcase %> ALBUM!</h1>


<form class="new_album" action=" <%= albums_url %> " method="post">
  <%= authen_form %>

  <label for="album_title">Title
    <input type="text" name="album[title]" value="">
  </label>
  <br><br>


  <label for="album_band">Band
    <select name="album[band]">
      <% Band.all.each do |band| %>
        <option value="<%= band.id %>" <%= @current_band == band ? "select" : "" %>>
          <%= band.name %>
        </option>
      <% end  %>
    </select>
  </label>
  <br><br>

  <label for="album_type">Live
    <input type="radio" name="album[alb_type]" value="Live"
     <%= @album.alb_type == 'Live' ? 'checked' : '' %> >
  </label>
  <label for="album_type">Studio
    <input type="radio" name="album[alb_type]" value="Studio"
     <%= @album.alb_type == 'Studio' ? 'checked' : '' %> >
  </label>
  <br><br>

  <label for="album_year">Year
    <input type="text" name="album[year]" value="">
  </label>
  <br><br>

  <input type="submit" value="Submit">

</form>

W4D5/muisic_app/app/views/albums/show.html.erb
<h1><%= @album.title %></h1>


<div class="album_option">
  <h4>LINKS</h4>
  <%= button_to "New track", new_album_track_url(@album), method: :get %>
  <%= button_to "Edit Album", edit_album_url(@album), method: :get %>
  <%= button_to "Destroy Album", album_url(@album), method: :delete %>
  <%= button_to "Back to #{@album.band.name}", band_url(@album.band), method: :get %>

</div>

W4D5/muisic_app/app/views/bands/_form.html.erb
<% if type == :new
      action = bands_url
      method = "post"
   else
     action = band_url(band)
     method = "post"
   end  %>

<form action="<%= action %>" method="<%= method %>">

  <% if type == :edit %>
      <input type="hidden" name="_method" value="patch">
  <% end  %>
  <%= authen_form %>

  <label for="band_name">Name
    <input type="text" name="band[name]" value="<%= type == :edit ? band.name : "" %>">
  </label>

  <input type="submit" value="Submit">
</form>

W4D5/muisic_app/app/views/bands/edit.html.erb
<h1>Update <%= @band.name %>!</h1>

<%= render "form", band: @band, type: :edit %>

W4D5/muisic_app/app/views/bands/index.html.erb
<header>BANDS</header>

<ul>
  <% @bands.each do |band| %>
    <%= link_to band.name, band_url(band) %>
    <br><br>
  <% end %>
</ul>

<%= button_to "New band", new_band_url, method: :get %>

W4D5/muisic_app/app/views/bands/new.html.erb
<h1>NEW BAND!</h1>

<%= render "form", band: @band, type: :new %>

W4D5/muisic_app/app/views/bands/show.html.erb
<h1> <%= @band.name.upcase %> </h1>

<h2>ALBUMS</h2>
<section class='albums'>
  <% @band.albums.each do |album| %>
    <%= link_to album.title, album_url(album) %>
    <br>
  <% end %>
</section>



<div class="band_option">
  <h4>LINKS</h4>
  <%= button_to "New album", new_band_album_url(@band), method: :get %>
  <%= button_to "Edit Band", edit_band_url, method: :get %>
  <%= button_to "Destroy Band", band_url(@band), method: :delete %>
  <%= button_to "All Bands", bands_url, method: :get %>

</div>

W4D5/muisic_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuisicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <header>
        Music App
      </header>
      <div>
        <% if current_user.nil? %>
          <%= link_to "Sign Up", new_user_url %>
          <%= link_to "Log In", new_session_url %>
        <% else %>
          <%= button_to "Log out", session_url, method: :delete %>
        <% end %>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

W4D5/muisic_app/app/views/tracks/new.html.erb
<h1>NEW <%= @current_album.title.upcase %> ALBUM!</h1>


<form class="new_track" action=" <%= tracks_url %> " method="post">
  <%= authen_form %>

  <label for="track_title">Title
    <input type="text" name="track[title]" value="">
  </label>
  <br><br>


  <label for="track_band">Band
    <select name="track[album_id]">
      <% Album.all.each do |album| %>
        <option value="<%= album.id %>" <%= @current_album == album ? "select" : "" %>>
          <%= album.title  %>
        </option>
      <% end  %>
    </select>
  </label>
  <br><br>

  <label for="track_type">Regular
    <input type="radio" name="track[track_type]" value="Regular"
     <%= @track.track_type == 'Regular' ? 'checked' : '' %> >
  </label>
  <label for="track_type">Bonus
    <input type="radio" name="album[alb_type]" value="Bonus"
     <%= @track.track_type == 'Bonus' ? 'checked' : '' %> >
  </label>
  <br><br>

  <!-- <label for="album_year">Year
    <input type="text" name="album[year]" value="">
  </label>
  <br><br> -->
  <label for="lyrics">
    <textarea name="track[lyric]" rows="8" cols="80"></textarea>
  </label>

  <input type="submit" value="Submit">

</form>

W4D5/muisic_app/app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>


<div class="track_option">
  <h4>LINKS</h4>
  <%#= button_to "New track", new_track_url, method: : %>
  <%= button_to "Edit Track", edit_track_url(@track), method: :get %>
  <%= button_to "Destroy Track", track_url(@track), method: :delete %>
  <%= button_to "Back to #{@track.album.name}", album_url(@track.album), method: :get %>

</div>

W4D5/muisic_app/app/views/users/new.html.erb
<section class='signup_form'>
  <h2>Sign Up</h2>

  <form class="signup" action="<%= users_url %>" method="post">
    <!-- <input type="hidden" name="_method" value="patch"> -->
    <%= authen_form %>

    <label for="user_email">Email
      <input id="user_email" type="text"
        name="user[email]" >
    </label>
    <br><br>
    <label for="user_password">Password
      <input id="user_password" type="password"
        name="user[password]" >
    </label>
    <br><br>

    <input type="submit" value="Create User!">

  </form>
</section>

W4D5/muisic_app/app/views/users/show.html.erb
<h1>Hello <%= @user.email %></h1>